import { Dice, Equipment, StickerItem, MapNode } from '../types/game';

export const INITIAL_PLAYER_STATS = {
  maxHp: 60,
  hp: 60,
  gold: 40,
  maxControl: 3,
  maxEquipmentSlots: 5,
};

export const INITIAL_DICE_POOL: Dice[] = [
  {
    id: 'dice_starter_1',
    name: '先鋒普通骰 (Vanguard)',
    dieType: 'd6',
    colorTheme: 'ruby',
    faces: [
      { id: 'f1', baseValue: 1, element: 'normal' },
      { id: 'f2', baseValue: 2, element: 'normal' },
      { id: 'f3', baseValue: 3, element: 'normal' },
      { id: 'f4', baseValue: 4, element: 'normal' },
      { id: 'f5', baseValue: 5, element: 'normal' },
      { id: 'f6', baseValue: 6, element: 'normal' },
    ],
  },
  {
    id: 'dice_starter_2',
    name: '燃火熾炎骰 (Pyro)',
    dieType: 'd6',
    colorTheme: 'amber',
    faces: [
      { id: 'f7', baseValue: 1, element: 'fire' },
      { id: 'f8', baseValue: 2, element: 'normal' },
      { id: 'f9', baseValue: 3, element: 'fire' },
      { id: 'f10', baseValue: 3, element: 'normal' },
      { id: 'f11', baseValue: 4, element: 'fire' },
      { id: 'f12', baseValue: 5, element: 'fire' },
    ],
  },
  {
    id: 'dice_starter_3',
    name: '疾風疾雷骰 (Storm)',
    dieType: 'd6',
    colorTheme: 'sapphire',
    faces: [
      { id: 'f13', baseValue: 2, element: 'wind' },
      { id: 'f14', baseValue: 2, element: 'thunder' },
      { id: 'f15', baseValue: 3, element: 'wind' },
      { id: 'f16', baseValue: 4, element: 'thunder' },
      { id: 'f17', baseValue: 4, element: 'wind' },
      { id: 'f18', baseValue: 5, element: 'thunder' },
    ],
  },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq_fire_pair',
    name: '雙炎共鳴符 (Pyro Resonance)',
    type: 'pattern',
    rarity: 'rare',
    description: '同時擲出「火3」與「火5」時，額外造成 15 點爆發火傷！',
    iconName: 'Flame',
    ruleId: 'FIRE_3_5_COMBO',
    value: 15,
  },
  {
    id: 'eq_control_talisman',
    name: '操縱者護符 (Control Talisman)',
    type: 'control',
    rarity: 'common',
    description: '每場戰鬥最大 Control +1。',
    iconName: 'RotateCcw',
    ruleId: 'EXTRA_CONTROL',
    value: 1,
  },
];

export const ALL_EQUIPMENT_CATALOG: Equipment[] = [
  {
    id: 'eq_fire_pair',
    name: '雙炎共鳴符',
    type: 'pattern',
    rarity: 'rare',
    description: '同時擲出「火3」與「火5」時，額外造成 15 點爆發火傷！',
    iconName: 'Flame',
    ruleId: 'FIRE_3_5_COMBO',
    value: 15,
  },
  {
    id: 'eq_control_talisman',
    name: '操縱者護符',
    type: 'control',
    rarity: 'common',
    description: '每場戰鬥最大 Control +1。',
    iconName: 'RotateCcw',
    ruleId: 'EXTRA_CONTROL',
    value: 1,
  },
  {
    id: 'eq_overload_six',
    name: '超載雙六核',
    type: 'pattern',
    rarity: 'rare',
    description: '本回合出現兩顆以上「6點」時，恢復 1 點 Control 並追加 12 點雷擊！',
    iconName: 'Zap',
    ruleId: 'DUAL_SIX_OVERLOAD',
    value: 12,
  },
  {
    id: 'eq_element_trio',
    name: '三相元素交響',
    type: 'pattern',
    rarity: 'legendary',
    description: '本回合同時出現 火、風、雷 三種屬性時，總結算傷害提升 30%！',
    iconName: 'Sparkles',
    ruleId: 'TRI_ELEMENT_HARMONY',
    value: 30,
  },
  {
    id: 'eq_pyro_mastery',
    name: '烈焰加壓閥',
    type: 'global',
    rarity: 'common',
    description: '所有「火屬性」骰面傷害基礎 +2。',
    iconName: 'FlameKindling',
    ruleId: 'GLOBAL_FIRE_BOOST',
    value: 2,
  },
  {
    id: 'eq_storm_edge',
    name: '風暴加速器',
    type: 'global',
    rarity: 'common',
    description: '所有「風」與「雷」骰面傷害基礎 +1。',
    iconName: 'Wind',
    ruleId: 'GLOBAL_STORM_BOOST',
    value: 1,
  },
  {
    id: 'eq_heavy_impact',
    name: '重磅研磨機',
    type: 'global',
    rarity: 'rare',
    description: '所有點數 ≥ 5 的骰面，額外造成 +3 點粉碎傷害。',
    iconName: 'ShieldAlert',
    ruleId: 'HIGH_ROLL_BOOST',
    value: 3,
  },
  {
    id: 'eq_odd_strike',
    name: '奇數狂潮符文',
    type: 'pattern',
    rarity: 'rare',
    description: '若本回合至少出現 3 顆奇數骰子，觸發全體暴擊 (+8 傷害)！',
    iconName: 'Layers',
    ruleId: 'ODD_STREAK',
    value: 8,
  },
];

export const ALL_STICKERS_CATALOG: StickerItem[] = [
  {
    id: 'st_normal_4',
    name: '精鍛鐵面 [普4]',
    isDisposable: false,
    baseValue: 4,
    element: 'normal',
    description: '永久覆蓋骰面為普通4。',
    rarity: 'common',
    rewardTier: 'early',
  },
  {
    id: 'st_fire_5',
    name: '引火刻印 [火5]',
    isDisposable: false,
    baseValue: 5,
    element: 'fire',
    description: '永久覆蓋骰面為火5。',
    rarity: 'common',
    rewardTier: 'early',
  },
  {
    id: 'st_wind_6',
    name: '疾風刻印 [風6]',
    isDisposable: false,
    baseValue: 6,
    element: 'wind',
    description: '永久覆蓋骰面為風6。',
    rarity: 'common',
    rewardTier: 'early',
  },
  {
    id: 'st_thunder_8',
    name: '雷鳴刻印 [雷8]',
    isDisposable: false,
    baseValue: 8,
    element: 'thunder',
    description: '永久覆蓋骰面為雷8。',
    rarity: 'rare',
    rewardTier: 'early',
  },
  {
    id: 'st_fire_8',
    name: '熾炎核芯 [火8]',
    isDisposable: false,
    baseValue: 8,
    element: 'fire',
    description: '永久覆蓋骰面為「火屬性 8點」。突破基礎骰面！',
    rarity: 'common',
    cost: 20,
    rewardTier: 'mid',
  },
  {
    id: 'st_fire_12',
    name: '炎帝天罰 [火12]',
    isDisposable: false,
    baseValue: 12,
    element: 'fire',
    description: '永久覆蓋骰面為「火屬性 12點」。超魄力大火，強烈推薦！',
    rarity: 'rare',
    cost: 34,
    rewardTier: 'late',
  },
  {
    id: 'st_wind_9',
    name: '狂嵐神速 [風9]',
    isDisposable: false,
    baseValue: 9,
    element: 'wind',
    description: '永久覆蓋骰面為「風屬性 9點」。',
    rarity: 'common',
    cost: 22,
    rewardTier: 'mid',
  },
  {
    id: 'st_wind_13',
    name: '天劫颶風 [風13]',
    isDisposable: false,
    baseValue: 13,
    element: 'wind',
    description: '永久覆蓋骰面為「風屬性 13點」。超高風力輸出！',
    rarity: 'rare',
    cost: 36,
    rewardTier: 'late',
  },
  {
    id: 'st_thunder_10',
    name: '天怒神殛 [雷10 + Chain]',
    isDisposable: false,
    baseValue: 10,
    element: 'thunder',
    special: 'chain',
    description: '永久：造成10點雷傷，並引爆全場骰面 +2 點連鎖！',
    rarity: 'rare',
    cost: 38,
    rewardTier: 'mid',
  },
  {
    id: 'st_thunder_14',
    name: '萬鈞狂雷 [雷14 + Chain]',
    isDisposable: false,
    baseValue: 14,
    element: 'thunder',
    special: 'chain',
    description: '永久：造成14點巨額雷傷並引爆連鎖！毀滅級雷暴！',
    rarity: 'legendary',
    cost: 55,
    rewardTier: 'late',
  },
  {
    id: 'st_ice_9',
    name: '極霜冰魄 [冰9 + Shield]',
    isDisposable: false,
    baseValue: 9,
    element: 'ice',
    special: 'shield',
    description: '永久覆蓋骰面為「冰屬性 9點 + 9點護盾」。',
    rarity: 'common',
    cost: 24,
    rewardTier: 'mid',
  },
  {
    id: 'st_ice_13',
    name: '永恆零度 [冰13 + Shield]',
    isDisposable: false,
    baseValue: 13,
    element: 'ice',
    special: 'shield',
    description: '永久：造成13點冰傷並提供 13 點堅厚護盾！',
    rarity: 'rare',
    cost: 38,
    rewardTier: 'late',
  },
  {
    id: 'st_crit_crush',
    name: '狂暴重擊 [普15 + Crit]',
    isDisposable: false,
    baseValue: 15,
    element: 'normal',
    special: 'crit',
    description: '永久：高達15點粉碎傷害並觸發全體暴擊！極致單點毀滅爽感！',
    rarity: 'legendary',
    cost: 60,
    rewardTier: 'late',
  },
  {
    id: 'st_echo_fire',
    name: '神聖迴響 [火9 + Echo]',
    isDisposable: false,
    baseValue: 9,
    element: 'fire',
    special: 'echo',
    description: '永久：造成9點火傷，並額外複製上一顆骰子的傷害！',
    rarity: 'legendary',
    cost: 50,
    rewardTier: 'late',
  },
  {
    id: 'st_wild_prism',
    name: '創世全能核 [普10 + Wild]',
    isDisposable: false,
    baseValue: 10,
    element: 'normal',
    special: 'wild',
    description: '永久：10點萬能元素，輕易滿足各類裝備圖騰條件！',
    rarity: 'legendary',
    cost: 52,
    rewardTier: 'mid',
  },
  {
    id: 'st_normal_11',
    name: '鋼鐵巨錘 [普11]',
    isDisposable: false,
    baseValue: 11,
    element: 'normal',
    description: '永久覆蓋骰面為「普通 11點」。樸實而剛猛！',
    rarity: 'common',
    cost: 20,
    rewardTier: 'mid',
  },

  {
    id: 'st_disp_meteor_15',
    name: '『一次性』末日爆星 [火15]',
    isDisposable: true,
    baseValue: 15,
    element: 'fire',
    description: '整場戰鬥有效！戰前貼附後該場戰鬥持續生效為火15，戰鬥結束後恢復原骰面。',
    rarity: 'rare',
    cost: 25,
  },
  {
    id: 'st_disp_supercharge_18',
    name: '『一次性』超能神霄 [雷18]',
    isDisposable: true,
    baseValue: 18,
    element: 'thunder',
    description: '整場戰鬥有效！18點極限毀滅神雷，戰鬥結束後自動脫落。',
    rarity: 'legendary',
    cost: 35,
  },
  {
    id: 'st_disp_frostnova_14',
    name: '『一次性』絕對凍域 [冰14 + Shield]',
    isDisposable: true,
    baseValue: 14,
    element: 'ice',
    special: 'shield',
    description: '整場戰鬥有效！造成14點冰傷並提供14點格擋護盾，戰鬥結束後恢復。',
    rarity: 'rare',
    cost: 28,
  },
  {
    id: 'st_disp_typhoon_16',
    name: '『一次性』極境神颶 [風16 + Chain]',
    isDisposable: true,
    baseValue: 16,
    element: 'wind',
    special: 'chain',
    description: '整場戰鬥有效！16點風傷並連鎖引爆全場，戰鬥結束後恢復。',
    rarity: 'legendary',
    cost: 36,
  },
];


export const INITIAL_MAP_NODES: MapNode[] = [
  { id: 0, type: 'fight', enemyId: 'bubble_slime', title: '森林邊緣', description: '遭遇鼓泡史萊姆', completed: false, current: true },
  { id: 1, type: 'fight', enemyId: 'rock_goblin', title: '林間小徑', description: '遭遇投石哥布林・喀啦', completed: false, current: false },
  { id: 2, type: 'chest', title: '迷霧寶箱', description: '獲取貼紙包或珍稀裝備', completed: false, current: false },
  { id: 3, type: 'shop', title: '地精黑市', description: '購買一次性貼紙、裝備與補給', completed: false, current: false },
  { id: 4, type: 'fight', enemyId: 'thorn_boar', title: '荊棘坡道', description: '遭遇荊背岩豬', completed: false, current: false },
  { id: 5, type: 'elite', enemyId: 'moss_colossus', title: '苔冠石庭', description: '挑戰苔冠巨像', completed: false, current: false },
  { id: 6, type: 'chest', title: '古代密室', description: '獲取貼紙包或珍稀裝備', completed: false, current: false },
  { id: 7, type: 'shop', title: '流浪商人', description: '整備裝備與補給生命', completed: false, current: false },
  { id: 8, type: 'boss', enemyId: 'mistroot_mur', title: '霧冠樹心', description: '決戰霧冠古樹穆爾', completed: false, current: false },
];
