import { CREATURE_BALANCE as b } from './creatureBalanceConfig';
import { ARROW_DESCRIPTION } from '../directionalStickerConfig';
import type { CreatureId } from '../../types/creatures';
export const CREATURE_SKILL_INTRO: Record<CreatureId, string> = {
  arrowUp: ARROW_DESCRIPTION, arrowDown: ARROW_DESCRIPTION, arrowLeft: ARROW_DESCRIPTION, arrowRight: ARROW_DESCRIPTION,
  blank: '依骰面點數攻擊。',
  family: `同骰每有 1 個其他土人家族，攻擊力 +${b.family.bonusPerFace}，且自身的 buff 額外生效一次。`,
  sisters: `自身得到外部攻擊加成時，其他朝上的土人姐妹花各獲得該加成值 ×${b.sisters.shareMultiplier}。`,
  twins: `攻擊力變為同骰土人雙胞胎中的最高值；且同骰每湊齊 ${b.twins.facesPerPair} 個土人雙胞胎，額外攻擊一次`,
  gang: `同骰每有 1 個相鄰的其他土人混混，產生 1 次追加攻擊，傷害為自身基礎攻擊力的 ${b.gang.fraction * 100}%。`,
  boss: `搶奪另一名 [普通] 土人的全部攻擊力。本回合每有過 1 次成功的搶奪，本次奪得的攻擊力額外增加 ${b.boss.perRobbery * 100}%`,
  loner: `同骰沒有其他土人獨行俠時，自身攻擊力 ×${b.loner.multiplier}；若自身擁有 buff 且攻擊力為全場最高，額外再攻擊一次。`,
  chef: "同骰擲出 [食物] 時，轉化為「存糧」。 所有同骰內的土人廚師平分存糧，各自產生 1 次等值傷害的追加攻擊，之後清空存糧",
  porter: "自身攻擊力增加同一連線前方所有土人搬運工的攻擊力總和。",
  follower: `獲得左右鄰骰中攻擊力最高的土人勇士 ${b.follower.fraction * 100}% 基礎攻擊力。同骰每有 1 個其他土人跟班，取得比例再 +${b.follower.perFace * 100}%`,
  cheerleader: "所有朝上的 [戰士] 攻擊力增加同骰「土人啦啦隊」面數。並各自發動 1 次追加攻擊，造成等同該增加數值的傷害。",
  thief: "每發生一次搶奪，自身發動一次追加攻擊，傷害為同骰內所有土人毛賊的基礎攻擊力總和",
  coward: "被重骰時，將自身的基礎攻擊力轉換為護盾；每顆骰子每回合最多觸發一次。",
  guard: "場上每有 1 位 [普通] 或 [貴族] 土人，自身獲得護盾；數值等於同骰中土人侍衛的數量",
  warrior: `左右鄰骰中每有 1 個土人跟班，自身攻擊力 +${b.warrior.bonusPerFollower}；左右每 1 面朝上的土人跟班，自身攻擊力再 +${b.warrior.perFacingFollower * 100}%`,
  elder: `場上所有非白板的土人，其同骰內每有 1 個相同的土人，該土人的攻擊力 +${b.elder.bonusPerFace}。`,
  artisan: `同骰每有 1 個相鄰的 [職人]，獲得 ${b.artisan.shield} 護盾；若該相鄰面為土人工匠，額外獲得等同其基礎攻擊力的護盾`,
  priest: "此骰每重骰一次，獲得 1 層「犧牲」；每層犧牲使場上每名土人祭司造成 1 次追加攻擊，傷害等同本面基礎攻擊力。",
  knight: `場上每有 1 名其他 [普通] 土人，自身攻擊力 + ${b.knight.bonus}；若左右兩側朝上的土人皆為 [普通]，本回合自身追加 [貴族] 標籤`,
  teacher: `選擇場上 1 顆基礎攻擊力最低的骰子強制重骰；若重骰後的基礎攻擊力比原本高，本回合全隊每累計重骰一次，該土人的攻擊力 +${b.teacher.bonus}。`,
  royalGuard: "獲得 buff 時，同骰每有 1 個其他 [貴族] ，自身額外獲得一次該 buff。",
  prankster: `自身被重骰時，重骰所有相鄰骰子；各骰子原骰面基礎攻擊力的 ${b.prankster.inheritance * 100}% 在本回合會傳承給重骰出的新骰面`,
  authority: `本回合將相鄰的所有 [普通] 土人增加 [貴族] 標籤。場上每有 1 名其他 [貴族]，受影響的土人 +${b.authority.bonusPerNoble} 攻擊力`,
  farmer: "若場上沒有 [食物]，土人農夫本回合轉化為好吃的；若已有 [食物]，使距離最近的 [食物] 攻擊力增加「其同骰內土人農夫與 [食物] 面總數」",
  imposter: "偽裝為場上數量最多（至少 2 個，平手隨機）的其他非白板土人或 [食物]。若場上數量皆小於 2，改檢視同骰內；若仍無滿足條件者，維持原樣。",
  glutton: "場上每 1 份朝上的 [食物]，使自身攻擊力增加該食物同骰內所有 [食物] 的基礎攻擊力總和。",
  bulwark: "追加 1 次攻擊，造成等同現有護盾值的傷害；本回合每獲得 1 次護盾，該次追加攻擊傷害再 + 自身的基礎攻擊力。",
  bully: `搶奪所有相鄰土人各 50% 的攻擊力作為保護費，以 ${b.bully.multiplier} 倍轉化成自己的攻擊力；若目標為 [職人]，自身額外獲得一次保護費，並額外計為一次成功搶奪`,
  herald: `每發動一次「追加攻擊」，全員各增加 ${b.herald.bonusPerAttack} 點攻擊力；每有 1 位朝上的土人號角手，使所有追加攻擊傷害 +${b.herald.bonusDiceDamage}。`,
  princess: "基礎攻擊力為 0。命令場上所有其他 [貴族] 土人額外攻擊一次。",
  detective: `本回合所有發動過搶奪的土人攻擊力歸零；自身獲得所沒收攻擊力總和的 ${b.detective.multiplier} 倍。`,
  fruit: `給左右鄰骰各 +${b.fruit.bonus} 攻擊力；場上有其他 [食物] 時，改為各 +${b.fruit.highBonus} 攻擊力；額外以自身攻擊力存糧；每個土人廚師額外增加 ${b.chef.storagePerFace} 存糧。`,
  food: `額外以 ${b.food.storageMultiplier} 倍的攻擊力存糧；每個土人廚師額外增加 ${b.chef.storagePerFace} 存糧。`,
};
export const creatureDescription = (id: CreatureId) => CREATURE_SKILL_INTRO[id];
