export const CREATURE_BALANCE = {
  family: { multipliers: [100, 150, 2, 2.5, 3.2, 4] },
  sisters: { minimum: 2, middle: 3, repeatAt: 4, multiplier: 2, highMultiplier: 2.5 },
  twins: { halfAt: 2, fullAt: 4, doubleAt: 6, half: 0.5 },
  gang: { middle: 3, doubleAt: 4, damagePerNeighbor: 2, highDamage: 3, copies: 2 },
  boss: { multipliers: [1.2, 1.5, 2] },
  loner: { multiplier: 2, soloMultiplier: 2.5 },
  chef: { retainAt: 25, burstAt: 50, retention: 0.2, highRetention: 0.4, multiplier: 1.5 },
  porter: { doubleAt: 3, tailAt: 4, repeatAt: 5, multiplier: 2 },
  follower: { range: 1, repeatMultiplier: 0.5 },
  cheerleader: { bonusPerWarrior: 1, copyAt: 4 },
  guard: { threshold: 4, shield: 1, highShield: 3 },
  warrior: { bonusPerFollower: 2, middle: 4, high: 8, multiplier: 2.5, highMultiplier: 3 },
  elder: { middle: 4, high: 6, bonusPerSpecies: 1, middleBonus: 2, highBonus: 3 },
  artisan: { threshold: 3, shield: 2, highShield: 4 },
  priest: { middle: 3, splitAt: 5, damagePerReroll: 5, middleDamage: 10, highDamage: 15 },
  knight: { nobleAt: 4, burstAt: 5, bonus: 3, highBonus: 4, multiplier: 1.5 },
  teacher: { bonus: 3 },
  royalGuard: { threshold: 4, bonusPerNoble: 3, highBonus: 5 },
  authority: { threshold: 3, bonus: 0.5 },
  farmer: { threshold: 3, foodBonus: 3 },
  fruit: { bonus: 2, highBonus: 4 },
  glutton: { perFood: [0.5, 0.8, 1.2, 1.5], sumAt: 4, hungryMultiplier: 0.9 },
  bulwark: { middle: 15, high: 30, lowMultiplier: 0.7, multiplier: 1, highMultiplier: 1.5 },
  bully: { stolenFraction: 0.5, multiplier: 1.2, craftsmanMultiplier: 2 },
  detective: { multiplier: 1.2 },
  herald: { threshold: 10, bonusPerAttack: 1, highBonus: 2, bonusDiceDamage: 1 },
  princess: { packLimit: 2, packChance: 0.05, guaranteedNode: 2 },
} as const;
